### ISSUE TITLE
The camera FPS is low on Hololens2

### ISSUE THREAD

**Issue by jianchong-chen** [MicrosoftDocs/windows-uwp.zh-cn#7]
Thanks for your sharing. 
I used the code to process the video with my algorithm.
It' running OK on Hololens 1, but gets low FPS(~6-7FPS) on Hololens 2.
Could you tell me how can I modify the code to run on HL2?
Thank you!

**Comment by srvbpigh** [comment]
Hello, @jianchong-chen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jianchong-chen** [comment]
@srvbpigh Thanks for your help!

**Comment by CeciAc** [comment]
Hello, @jianchong-chen 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
